### ISSUE TITLE
the case of email of "name@abc" is passed?

### ISSUE THREAD

**Issue by tuanquynet** [themeteorchef/jquery-validation#1] opened 2015-02-13 09:47 UTC
But this case is not passed with original library from https://github.com/jzaefferer/jquery-validation

**Comment by themeteorchef** [comment] 2015-02-13 16:31
Hmm. No changes from the original library (just a thin wrapper, here). Could you share a snippet of the code you're using to get this result?

**Comment by nathanhornby** [comment] 2015-08-18 14:34
@themeteorchef I can reproduce this, but it's no different to many other forms of email validation.

Chrome's built in validation for inputs with an 'email' type will also accept 'name@abc'. Basic snippet for quick testing: https://jsfiddle.net/tsf1n1r0/

I can only assume that this is for a good reason - as it seems like it'd be easy to check for the presence of a dot after the @ sign. Maybe there are cases where that's valid? (having looked at the spec for email address validation before, it's immensely complicated if you want to accurately capture all invalid cases)

**Comment by themeteorchef** [comment] 2015-09-09 20:00
@nathanhornby @tuanquynet sorry for dropping off on this. 

This seems to be more of an issue with the original library than anything else. @nathanhornby mentioned another feature that was missing due to one of the sub-libraries not being included. Is this validation potentially in the mix with those other sub-libraries? If it is, it may be worth adding all as that seems to be the more common cause of validations/features not existing.

Let me know so we can get it updated!

**Comment by nathanhornby** [comment] 2015-09-09 20:20
Your call, but I personally think the regex addition allows for special cases - wouldn't including all of the sub libraries be a bloat issue?

**Comment by themeteorchef** [comment] 2015-09-09 20:37
I'd rather not fork the original library as that has the potential for some interesting conflicts down the road.

Re: sub-libraries, yes, which is why I originally left them out. Only thought here is to add them on a case-by-case basis, though, a fix for this problem being in one of those libraries is only speculation at the moment.

**Closed as completed** 2015-10-08 14:20 UTC
